FROM ubuntu-with-cache

RUN apt-get update \
    && apt-get install -y --no-install-suggests --no-install-recommends \
    cowsay \
    && rm -rf /var/lib/apt/lists/*

CMD ["/usr/games/cowsay", "Does electric sheep…"]
